"""add_company_research_fields

Revision ID: 9f21df31cf47
Revises: 
Create Date: 2026-04-10 11:58:38.189338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f21df31cf47'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_research', sa.Column('employee_count', sa.String(), nullable=True))
    op.add_column('company_research', sa.Column('industry', sa.String(), nullable=True))
    op.add_column('company_research', sa.Column('summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_research', 'summary')
    op.drop_column('company_research', 'industry')
    op.drop_column('company_research', 'employee_count')
    # ### end Alembic commands ###
